export const Routes = {
  base: "",
  login: "login",
  profile: "profile",
  catalog: "catalog",
  delivery: "delivery",
  questions: "questions",
  contacts: "contacts",
  aboutUs: "about-us",
  basket: "catalog/basket",
  checkout: "basket/checkout",
  heart: "heart",
  admin: "admin",
  adminAdd: "/admin/add",
  adminOrder: "/admin/order",
  adminInfo: "/admin/info",
};
